### ISSUE TITLE
Small manual for self-compiling container

### ISSUE THREAD

**Issue by Thijmen** [chilio/laravel-dusk-ci#6]
Hi,

I think it would be helpful if we had a manual on how to create your own container from this build. For me, I would like to have the nginx-error logs as I am getting some. 

Therefore, I would like to change the `error_log` path of nginx to the build root, as we cannot add artifacts outside the build directory.

**Comment by chilio** [comment]
in this regard, you are true, as for now, this repo, using it with with gitlab-runner, does not enable collecting artifacts from directories outside of project root. 
This is caused by gitlab-runners specific implementation.

You can always add/modify things to suite your needs in gitlab-ci scripts, most of them (linux commands) should work out of the box.

Putting logs in website root, doesn't seem like a good idea to me, regarding security.
But on the other hand, this container is always started once (with different id) via docker image in a secured CI environment. So it should not be too easy to hack.

Please post your php.ini and nginx.conf with site config,

Maybe I can customize it to your needs...

As for creating your own container... This is source with .dockerfile, so you can customize it anyway you want with docker build.

**Comment by Thijmen** [comment]
In my `after_script`, I copied the `/var/log/nginx/error.log` to `storage/log/`, which works :-) That way, I was able to resolve my issue. 

Thanks for putting this great image on GitHub!
